import { Movie } from "./types";

export const moviesStub: Movie[] = [
  {
    adult: false,
    backdrop_path: "/uhUO7vQQKvCTfQWubOt5MAKokbL.jpg",
    id: 693134,
    title: "Dune: Part Two",
    original_language: "en",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    poster_path: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    media_type: "movie",
    genre_ids: [878, 12],
    popularity: 427.28,
    release_date: "2024-02-27",
    video: false,
    vote_average: 8.6,
    vote_count: 13,
  },
  {
    adult: false,
    backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
    id: 1072790,
    title: "Anyone But You",
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    poster_path: "/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
    media_type: "movie",
    genre_ids: [35, 10749],
    popularity: 1589.046,
    release_date: "2023-12-21",
    video: false,
    vote_average: 6.9,
    vote_count: 551,
  },
  {
    adult: false,
    backdrop_path: "/dmiN2rakG9hZW04Xx7mHOoHTOyD.jpg",
    id: 673593,
    title: "Mean Girls",
    original_language: "en",
    original_title: "Mean Girls",
    overview:
      "New student Cady Heron is welcomed into the top of the social food chain by the elite group of popular girls called ‘The Plastics,’ ruled by the conniving queen bee Regina George and her minions Gretchen and Karen. However, when Cady makes the major misstep of falling for Regina’s ex-boyfriend Aaron Samuels, she finds herself prey in Regina’s crosshairs. As Cady sets to take down the group’s apex predator with the help of her outcast friends Janis and Damian, she must learn how to stay true to herself while navigating the most cutthroat jungle of all: high school.",
    poster_path: "/fbbj3viSUDEGT1fFFMNpHP1iUjw.jpg",
    media_type: "movie",
    genre_ids: [35],
    popularity: 272.588,
    release_date: "2024-01-10",
    video: false,
    vote_average: 6.5,
    vote_count: 154,
  },
  {
    adult: false,
    backdrop_path: "/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    id: 438631,
    title: "Dune",
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    media_type: "movie",
    genre_ids: [878, 12],
    popularity: 420.499,
    release_date: "2021-09-15",
    video: false,
    vote_average: 7.788,
    vote_count: 10143,
  },
  {
    adult: false,
    backdrop_path: "/2GzgongTSptjSkT7iCoXUcGIVB9.jpg",
    id: 994108,
    title: "All of Us Strangers",
    original_language: "en",
    original_title: "All of Us Strangers",
    overview:
      "One night in his near-empty tower block in contemporary London, Adam has a chance encounter with a mysterious neighbor Harry, which punctures the rhythm of his everyday life. As a relationship develops between them, Adam is preoccupied with memories of the past and finds himself drawn back to the suburban town where he grew up, and the childhood home where his parents appear to be living, just as they were on the day they died, 30 years before.",
    poster_path: "/zShZtXl2sMMCEodueSJM3cENNR8.jpg",
    media_type: "movie",
    genre_ids: [10749, 18, 14],
    popularity: 248.755,
    release_date: "2023-12-22",
    video: false,
    vote_average: 7.7,
    vote_count: 135,
  },
];
